In [ ]:
"This is python"

'This is python'

In [ ]:
2+2

4

In [ ]:
3+19

22

In [ ]:
89*90

8010

In [ ]:
2+2

4

In [ ]:
2+2
3*3

9

In [ ]:
print(2+2)
print(3*3)

4
9

In [ ]:
# This is a comment

In [ ]:
# This is a comment
2+2 # addition of two numbers

4

This is normal text


# Heading


**bold**


1. one
2. two
3. three


[Here's more information on Markdown](https://www.markdownguide.org/basic-syntax/)

In [ ]:
!ls

sample_data

# Creating a Variable

total_salary = (base_salary) * (1 + bonus_rate)

In [ ]:
base_salary = 100000
bonus_rate = 0.10

In [ ]:
total_salary = (base_salary) * (1 + bonus_rate)

In [ ]:
print(total_salary)

110000.00000000001

In [ ]:
text = "Data Analyst"
print(type(text))
help(str)

<class 'str'>
Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to 'utf-8'.
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __sizeof__(self, /)
 |      Return the size of the string in memory, in bytes.
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  capitalize(self, /)
 |      Return a capitalized version of the string.
 |
 |      More specifically, make the first character have upper case and the
 |      rest lower case.
 |
 |  casefold(self, /)
 |      Return a version of the string suitable for caseless comparisons.
 |
 |  center(self, width, fillchar=' ', /)
 |      Return a centered string of length width.
 |
 |      Padding is done using the specified fill character (default is
 |      a space).
 |
 |  count(self, sub[, start[, end]], /)
 |      Return the number of non-overlapping occurrences of substring sub in string S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice
 |      notation.
 |
 |  encode(self, /, encoding='utf-8', errors='strict')
 |      Encode the string using the codec registered for encoding.
 |
 |      encoding
 |        The encoding in which to encode the string.
 |      errors
 |        The error handling scheme to use for encoding errors.
 |        The default is 'strict' meaning that encoding errors raise a
 |        UnicodeEncodeError.  Other possible values are 'ignore', 'replace'
 |        and 'xmlcharrefreplace' as well as any other name registered with
 |        codecs.register_error that can handle UnicodeEncodeErrors.
 |
 |  endswith(self, suffix[, start[, end]], /)
 |      Return True if the string ends with the specified suffix, False otherwise.
 |
 |      suffix
 |        A string or a tuple of strings to try.
 |      start
 |        Optional start position. Default: start of the string.
 |      end
 |        Optional stop position. Default: end of the string.
 |
 |  expandtabs(self, /, tabsize=8)
 |      Return a copy where all tab characters are expanded using spaces.
 |
 |      If tabsize is not given, a tab size of 8 characters is assumed.
 |
 |  find(self, sub[, start[, end]], /)
 |      Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice
 |      notation.  Return -1 on failure.
 |
 |  format(self, /, *args, **kwargs)
 |      Return a formatted version of the string, using substitutions from args and kwargs.
 |      The substitutions are identified by braces ('{' and '}').
 |
 |  format_map(self, mapping, /)
 |      Return a formatted version of the string, using substitutions from mapping.
 |      The substitutions are identified by braces ('{' and '}').
 |
 |  index(self, sub[, start[, end]], /)
 |      Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice
 |      notation.  Raises ValueError when the substring is not found.
 |
 |  isalnum(self, /)
 |      Return True if the string is an alpha-numeric string, False otherwise.
 |
 |      A string is alpha-numeric if all characters in the string are
 |      alpha-numeric and there is at least one character in the string.
 |
 |  isalpha(self, /)
 |      Return True if the string is an alphabetic string, False otherwise.
 |
 |      A string is alphabetic if all characters in the string are
 |      alphabetic and there is at least one character in the string.
 |
 |  isascii(self, /)
 |      Return True if all characters in the string are ASCII, False otherwise.
 |
 |      ASCII characters have code points in the range U+0000-U+007F.
 |      Empty string is ASCII too.
 |
 |  isdecimal(self, /)
 |      Return True if the string is a decimal string, False otherwise.
 |
 |      A string is a decimal string if all characters in the string are
 |      decimal and there is at least one character in the string.
 |
 |  isdigit(self, /)
 |      Return True if the string is a digit string, False otherwise.
 |
 |      A string is a digit string if all characters in the string are
 |      digits and there is at least one character in the string.
 |
 |  isidentifier(self, /)
 |      Return True if the string is a valid Python identifier, False otherwise.
 |
 |      Call keyword.iskeyword(s) to test whether string s is a reserved
 |      identifier, such as "def" or "class".
 |
 |  islower(self, /)
 |      Return True if the string is a lowercase string, False otherwise.
 |
 |      A string is lowercase if all cased characters in the string are
 |      lowercase and there is at least one cased character in the string.
 |
 |  isnumeric(self, /)
 |      Return True if the string is a numeric string, False otherwise.
 |
 |      A string is numeric if all characters in the string are numeric and
 |      there is at least one character in the string.
 |
 |  isprintable(self, /)
 |      Return True if all characters in the string are printable, False otherwise.
 |
 |      A character is printable if repr() may use it in its output.
 |
 |  isspace(self, /)
 |      Return True if the string is a whitespace string, False otherwise.
 |
 |      A string is whitespace if all characters in the string are
 |      whitespace and there is at least one character in the string.
 |
 |  istitle(self, /)
 |      Return True if the string is a title-cased string, False otherwise.
 |
 |      In a title-cased string, upper- and title-case characters may only
 |      follow uncased characters and lowercase characters only cased ones.
 |
 |  isupper(self, /)
 |      Return True if the string is an uppercase string, False otherwise.
 |
 |      A string is uppercase if all cased characters in the string are
 |      uppercase and there is at least one cased character in the string.
 |
 |  join(self, iterable, /)
 |      Concatenate any number of strings.
 |
 |      The string whose method is called is inserted in between each given
 |      string.  The result is returned as a new string.
 |
 |      Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'
 |
 |  ljust(self, width, fillchar=' ', /)
 |      Return a left-justified string of length width.
 |
 |      Padding is done using the specified fill character (default is
 |      a space).
 |
 |  lower(self, /)
 |      Return a copy of the string converted to lowercase.
 |
 |  lstrip(self, chars=None, /)
 |      Return a copy of the string with leading whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  partition(self, sep, /)
 |      Partition the string into three parts using the given separator.
 |
 |      This will search for the separator in the string.  If the separator
 |      is found, returns a 3-tuple containing the part before the
 |      separator, the separator itself, and the part after it.
 |
 |      If the separator is not found, returns a 3-tuple containing
 |      the original string and two empty strings.
 |
 |  removeprefix(self, prefix, /)
 |      Return a str with the given prefix string removed if present.
 |
 |      If the string starts with the prefix string, return
 |      string[len(prefix):].  Otherwise, return a copy of the original
 |      string.
 |
 |  removesuffix(self, suffix, /)
 |      Return a str with the given suffix string removed if present.
 |
 |      If the string ends with the suffix string and that suffix is not
 |      empty, return string[:-len(suffix)].  Otherwise, return a copy of
 |      the original string.
 |
 |  replace(self, old, new, /, count=-1)
 |      Return a copy with all occurrences of substring old replaced by new.
 |
 |        count
 |          Maximum number of occurrences to replace.
 |          -1 (the default value) means replace all occurrences.
 |
 |      If the optional argument count is given, only the first count occurrences are
 |      replaced.
 |
 |  rfind(self, sub[, start[, end]], /)
 |      Return the highest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice
 |      notation.  Return -1 on failure.
 |
 |  rindex(self, sub[, start[, end]], /)
 |      Return the highest index in S where substring sub is found, such that sub is contained within S[start:end].
 |
 |      Optional arguments start and end are interpreted as in slice
 |      notation.  Raises ValueError when the substring is not found.
 |
 |  rjust(self, width, fillchar=' ', /)
 |      Return a right-justified string of length width.
 |
 |      Padding is done using the specified fill character (default is
 |      a space).
 |
 |  rpartition(self, sep, /)
 |      Partition the string into three parts using the given separator.
 |
 |      This will search for the separator in the string, starting at the
 |      end.  If the separator is found, returns a 3-tuple containing the
 |      part before the separator, the separator itself, and the part after
 |      it.
 |
 |      If the separator is not found, returns a 3-tuple containing two
 |      empty strings and the original string.
 |
 |  rsplit(self, /, sep=None, maxsplit=-1)
 |      Return a list of the substrings in the string, using sep as the separator string.
 |
 |        sep
 |          The separator used to split the string.
 |
 |          When set to None (the default value), will split on any
 |          whitespace character (including \n \r \t \f and spaces) and
 |          will discard empty strings from the result.
 |        maxsplit
 |          Maximum number of splits.
 |          -1 (the default value) means no limit.
 |
 |      Splitting starts at the end of the string and works to the front.
 |
 |  rstrip(self, chars=None, /)
 |      Return a copy of the string with trailing whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  split(self, /, sep=None, maxsplit=-1)
 |      Return a list of the substrings in the string, using sep as the separator string.
 |
 |        sep
 |          The separator used to split the string.
 |
 |          When set to None (the default value), will split on any
 |          whitespace character (including \n \r \t \f and spaces) and
 |          will discard empty strings from the result.
 |        maxsplit
 |          Maximum number of splits.
 |          -1 (the default value) means no limit.
 |
 |      Splitting starts at the front of the string and works to the end.
 |
 |      Note, str.split() is mainly useful for data that has been
 |      intentionally delimited.  With natural text that includes
 |      punctuation, consider using the regular expression module.
 |
 |  splitlines(self, /, keepends=False)
 |      Return a list of the lines in the string, breaking at line boundaries.
 |
 |      Line breaks are not included in the resulting list unless keepends
 |      is given and true.
 |
 |  startswith(self, prefix[, start[, end]], /)
 |      Return True if the string starts with the specified prefix, False otherwise.
 |
 |      prefix
 |        A string or a tuple of strings to try.
 |      start
 |        Optional start position. Default: start of the string.
 |      end
 |        Optional stop position. Default: end of the string.
 |
 |  strip(self, chars=None, /)
 |      Return a copy of the string with leading and trailing whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  swapcase(self, /)
 |      Convert uppercase characters to lowercase and lowercase characters to uppercase.
 |
 |  title(self, /)
 |      Return a version of the string where each word is titlecased.
 |
 |      More specifically, words start with uppercased characters and all
 |      remaining cased characters have lower case.
 |
 |  translate(self, table, /)
 |      Replace each character in the string using the given translation table.
 |
 |        table
 |          Translation table, which must be a mapping of Unicode ordinals
 |          to Unicode ordinals, strings, or None.
 |
 |      The table must implement lookup/indexing via __getitem__, for
 |      instance a dictionary or list.  If this operation raises
 |      LookupError, the character is left untouched.  Characters mapped to
 |      None are deleted.
 |
 |  upper(self, /)
 |      Return a copy of the string converted to uppercase.
 |
 |  zfill(self, width, /)
 |      Pad a numeric string with zeros on the left, to fill a field of the given width.
 |
 |      The string is never truncated.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  maketrans(x, y=<unrepresentable>, z=<unrepresentable>, /)
 |      Return a translation table usable for str.translate().
 |
 |      If there is only one argument, it must be a dictionary mapping
 |      Unicode ordinals (integers) or characters to Unicode ordinals,
 |      strings or None.  Character keys will be then converted to ordinals.
 |      If there are two arguments, they must be strings of equal length,
 |      and in the resulting dictionary, each character in x will be mapped
 |      to the character at the same position in y.  If there is a third
 |      argument, it must be a string, whose characters will be mapped to
 |      None in the result.

Varibles point to a specific object

In [ ]:
job_title = "Data Analyst"
job_location = "United States"
job_salary = 90000

In [ ]:
id(job_title)

132525878567280

In [ ]:
id(job_location)

132525878584560

In [ ]:
job_1 = "Data Analyst"
job_2 = "Data Analyst"
job_3 = job_1

print(id(job_1), id(job_2))
print(id(job_1), id(job_3))

132525876926768 132525876926576
132525876926768 132525876926768

In [ ]:
print("Hello World!")
my_print_func = print
my_print_func("Hello World!")

Hello World!
Hello World!

# Functions: The Manipulators of Objects
**Function**: A reusable piece of code that performs a specific task

In [ ]:
print

In [ ]:
job_title = "Data Analyst"
job_location = "United States"
job_salary = 90000

In [ ]:
print(f"JOB:        {job_title}\nLOCATION:   {job_location}\nSALARY:     ${job_salary:,.0f}")

JOB:        Data Analyst
LOCATION:   United States
SALARY:     $90,000

In [ ]:
def display_info(title, location, salary):
  return print(f"JOB:        {title}\nLOCATION:   {location}\nSALARY:     ${salary:,.0f}")

In [ ]:
display_info(job_title, job_location, job_salary)

JOB:        Data Analyst
LOCATION:   United States
SALARY:     $90,000

# Classes: The Template of Objects
**Class:** A template for creating objects (records)

In [ ]:
job_title = "Data Analyst"
job_location = "United States"
job_salary = 90000

In [ ]:
class JobPost:
  def __init__(self, title, location, salary):
    self.title = title
    self.location = location
    self.salary = salary

In [ ]:
JobPost(job_title, job_location, job_salary)

# Attributes: The Variables of an Object
**Attribute:** A field in a record, defined by its class

In [ ]:
class JobPost:
  def __init__(self, title, location, salary):
    self.title = title
    self.location = location
    self.salary = salary

In [ ]:
job_1 = JobPost(job_title, job_location, job_salary)

In [ ]:
job_1.title

'Data Analyst'

# Methods: The Functions of an Object
**Method:** A function defined inside a class that operates on its objects

In [ ]:
class JobPost:
  def __init__(self, title, location, salary):
    self.title = title
    self.location = location
    self.salary = salary
  def display_info(self):
    return print(f"JOB:        {self.title}\nLOCATION:   {self.location}\nSALARY:     ${self.salary:,.0f}")

In [ ]:
job_1 = JobPost(job_title, job_location, job_salary)

In [ ]:
job_1.location

'United States'

In [ ]:
job_1.display_info()

JOB:        Data Analyst
LOCATION:   United States
SALARY:     $90,000

In [ ]:
# Example on Methods

salary = 90000
type(salary)

int

In [ ]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating-point
 |  numbers, this truncates towards zero.
 |
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer
 |  iteral.
 |  >>> int('0b100', base=0)
 |  4
 |
 |  Built-in subclasses:
 |      bool
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __ceil__(self, /)
 |      Ceiling of an Integral returns itself.
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floor__(self, /)
 |      Flooring an Integral returns itself.
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __format__(self, format_spec, /)
 |      Convert to a string according to format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __index__(self, /)
 |      Return self converted to an integer, if self is suitable for use as an index into a list.
 |
 |  __int__(self, /)
 |      int(self)
 |
 |  __invert__(self, /)
 |      ~self
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lshift__(self, value, /)
 |      Return self<<value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __neg__(self, /)
 |      -self
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __pos__(self, /)
 |      +self
 |
 |  __pow__(self, value, mod=None, /)
 |      Return pow(self, value, mod).
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __rand__(self, value, /)
 |      Return value&self.
 |
 |  __rdivmod__(self, value, /)
 |      Return divmod(value, self).
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rfloordiv__(self, value, /)
 |      Return value//self.
 |
 |  __rlshift__(self, value, /)
 |      Return value<<self.
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __round__(self, ndigits=<unrepresentable>, /)
 |      Rounding an Integral returns itself.
 |
 |      Rounding with an ndigits argument also returns an integer.
 |
 |  __rpow__(self, value, mod=None, /)
 |      Return pow(value, self, mod).
 |
 |  __rrshift__(self, value, /)
 |      Return value>>self.
 |
 |  __rshift__(self, value, /)
 |      Return self>>value.
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __rtruediv__(self, value, /)
 |      Return value/self.
 |
 |  __rxor__(self, value, /)
 |      Return value^self.
 |
 |  __sizeof__(self, /)
 |      Returns size in memory, in bytes.
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  __truediv__(self, value, /)
 |      Return self/value.
 |
 |  __trunc__(self, /)
 |      Truncating an Integral returns itself.
 |
 |  __xor__(self, value, /)
 |      Return self^value.
 |
 |  as_integer_ratio(self, /)
 |      Return a pair of integers, whose ratio is equal to the original int.
 |
 |      The ratio is in lowest terms and has a positive denominator.
 |
 |      >>> (10).as_integer_ratio()
 |      (10, 1)
 |      >>> (-10).as_integer_ratio()
 |      (-10, 1)
 |      >>> (0).as_integer_ratio()
 |      (0, 1)
 |
 |  bit_count(self, /)
 |      Number of ones in the binary representation of the absolute value of self.
 |
 |      Also known as the population count.
 |
 |      >>> bin(13)
 |      '0b1101'
 |      >>> (13).bit_count()
 |      3
 |
 |  bit_length(self, /)
 |      Number of bits necessary to represent self in binary.
 |
 |      >>> bin(37)
 |      '0b100101'
 |      >>> (37).bit_length()
 |      6
 |
 |  conjugate(self, /)
 |      Returns self, the complex conjugate of any int.
 |
 |  is_integer(self, /)
 |      Returns True. Exists for duck type compatibility with float.is_integer.
 |
 |  to_bytes(self, /, length=1, byteorder='big', *, signed=False)
 |      Return an array of bytes representing an integer.
 |
 |      length
 |        Length of bytes object to use.  An OverflowError is raised if
 |        the integer is not representable with the given number of bytes.
 |        Default is length 1.
 |      byteorder
 |        The byte order used to represent the integer.  If byteorder is
 |        'big', the most significant byte is at the beginning of the byte
 |        array.  If byteorder is 'little', the most significant byte is at
 |        the end of the byte array.  To request the native byte order of
 |        the host system, use sys.byteorder as the byte order value.
 |        Default is to use 'big'.
 |      signed
 |        Determines whether two's complement is used to represent the
 |        integer.  If signed is False and a negative integer is given,
 |        an OverflowError is raised.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_bytes(bytes, byteorder='big', *, signed=False)
 |      Return the integer represented by the given array of bytes.
 |
 |      bytes
 |        Holds the array of bytes to convert.  The argument must either
 |        support the buffer protocol or be an iterable object producing
 |        bytes.  Bytes and bytearray are examples of built-in objects that
 |        support the buffer protocol.
 |      byteorder
 |        The byte order used to represent the integer.  If byteorder is
 |        'big', the most significant byte is at the beginning of the byte
 |        array.  If byteorder is 'little', the most significant byte is at
 |        the end of the byte array.  To request the native byte order of
 |        the host system, use sys.byteorder as the byte order value.
 |        Default is to use 'big'.
 |      signed
 |        Indicates whether two's complement is used to represent the
 |        integer.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  denominator
 |      the denominator of a rational number in lowest terms
 |
 |  imag
 |      the imaginary part of a complex number
 |
 |  numerator
 |      the numerator of a rational number in lowest terms
 |
 |  real
 |      the real part of a complex number

In [ ]:
salary.__add__(100)

90100

In [ ]:
'Data ' + "Nerd"

'Data Nerd'

In [ ]:
'Data Nerd'.capitalize()

'Data nerd'

In [ ]:
'Data Nerd'.upper()

'DATA NERD'

In [ ]:
'Data Nerd'.lower()

'data nerd'

In [ ]:
len("Data Nerd")

9

In [ ]:
job_id = 102
print(type(job_id))

job_id = float(102)
print(type(job_id))

<class 'int'>
<class 'float'>

# Strings

In [ ]:
"Strings can be defined in double quotes"

'Strings can be defined in double quotes'

In [ ]:
'Strings can be defined in single quotes'

'Strings can be defined in single quotes'

In [ ]:
skill = 'Python'

In [ ]:
type(skill)

str

In [ ]:
skill.upper()

'PYTHON'

In [ ]:
skill.lower()

'python'

In [ ]:
# Can also write the above examples as follows:

print(str.upper("Python"))
print(str.lower("Python"))

PYTHON
python

In [ ]:
len("Python")

6

In [ ]:
# replace() - replace(self, old, new, count=-1, /)
# count = -1 (by default) means replace all occurrences
# Otherwise, maximum no. of occurrences to replace
skill = "Python"
skill.replace('P', 'J')

'Jython'

In [ ]:
# Replace 'Data' with 'Doto'
job_title = 'Data Analyst'
job_title = job_title.replace('a', 'o', 2)
job_title

'Doto Analyst'

In [ ]:
# split()  -> split(self, /, sep=None, maxsplit=-1)
# sep      -> the separator used to split the string
# maxsplit -> max. no. of splits (starting from left)
# -1 (the default) means no limit

# split 'Doto Analyst' into 'Doto' and 'Analyst'
job_title.split(sep = " ", maxsplit = 1)

['Doto', 'Analyst']

In [ ]:
# Adding two strings
print('Data' + ' Analyst')
print(str.__add__('Data', ' Analyst'))
print('Data'.__add__(' Analyst'))

Data Analyst
Data Analyst
Data Analyst

In [ ]:
# Multiplying a string
print('Data Analyst\n' * 10)

Data Analyst
Data Analyst
Data Analyst
Data Analyst
Data Analyst
Data Analyst
Data Analyst
Data Analyst
Data Analyst
Data Analyst

In [ ]:
# Length of a string
print(str.__len__('Data Analyst'))
print(len('Data Analyst'))

12
12

# String Formatting

In [ ]:
role = 'Data Analyst'
skill = 'Python'

# METHOD-1: CONCATENATION

In [ ]:
# Write out 'Role: Data Analyst'

'Role: ' + role

'Role: Data Analyst'

# METHOD-2: str.format()

In [ ]:
'Role: {}'.format(role)

'Role: Data Analyst'

In [ ]:
# Create the string 'Role: Data Analyst; Skill Required: Python'

'Role: {}; Skill Required: {}'.format(role, skill)

'Role: Data Analyst; Skill Required: Python'

In [ ]:
# Can also be written as:

'Role: {job_role}; Skill Required: {job_skill}'.format(job_role=role, job_skill=skill)

'Role: Data Analyst; Skill Required: Python'

# METHOD-3: f-strings

In [ ]:
role = 'Data Analyst'
skill = 'Python'

In [ ]:
f"Role: {role}; Skill Required: {skill}"

'Role: Data Analyst; Skill Required: Python'

# METHOD-4: %-formatting (printf-style string formatting)

In [ ]:
'Role: %s; Skill Required: %s' %(role, skill)

'Role: Data Analyst; Skill Required: Python'

# METHOD-5: join()

In [ ]:
# Example - You want to separate the years of experience by ', '

years_experience = '0123456789'

', '.join(years_experience)

'0, 1, 2, 3, 4, 5, 6, 7, 8, 9'

In [ ]:
# Example - skills = ['Python', 'SQL', 'Excel']

skills = ['Python', 'SQL', 'Excel']

'; '.join(skills)

'Python; SQL; Excel'

# Operators

In [ ]:
# Dividing two nos. to get the actual value

5 / 2

2.5

In [ ]:
# Dividing two nos. to get the integer value

5 // 2

2

In [ ]:
# Dividing two nos. to get the remainder

5 % 2

1

### Order of Operations

- Parentheses: Anything in parentheses is executed first
- Exponents: Operations involving exponents (including roots, indicated as fractional exponents)
- Multiplication and Division: Processed from left to right
- Addition and Subtraction: Also processed from left to right

In [ ]:
min_salary = 20_000 # _ is ignored by interpreter
max_salary = 80_000

avg_salary = (min_salary + max_salary) / 2

print(avg_salary)

50000.0

### Assignment Operator

In [ ]:
# Method-1:

applicant_1 = 'Kelly'
applicant_2 = 'Luke'

temp = applicant_1
applicant_1 = applicant_2
applicant_2 = temp

applicant_1, applicant_2

('Luke', 'Kelly')

In [ ]:
# Method-2:

applicant_1 = 'Kelly'
applicant_2 = 'Luke'

applicant_1, applicant_2 = applicant_2, applicant_1

applicant_1, applicant_2

('Luke', 'Kelly')

# Conditional Statements

In [ ]:
job_skill = 'SQL'
applicant_skill = 'SQL'

if (job_skill == applicant_skill):
  print("Skills match!")

Skills match!

## Pass Keyword

The pass keyword in Python is a null operation statement that does absolutely nothing when executed

In [ ]:
# Examplez

x = 10

if x > 5:
    pass  # Placeholder for future logic
else:
    print("x is 5 or less")

## LISTS

In [ ]:
job_skills = ['SQL', 'Tableau', 'Excel']

In [ ]:
job_skills.append('Python')

In [ ]:
job_skills

['SQL', 'Tableau', 'Excel', 'Python']

In [ ]:
len(job_skills)

4

In [ ]:
job_skills.remove('Tableau')

In [ ]:
job_skills

['SQL', 'Excel', 'Python']

In [ ]:
len(job_skills)

3

In [ ]:
job_skills[1]

'Excel'

In [ ]:
job_skills.insert(2, 'Tableau')

In [ ]:
job_skills

['SQL', 'Excel', 'Tableau', 'Python']

In [ ]:
job_skills.pop() # takes the last index by default

'Python'

In [ ]:
job_skills

['SQL', 'Excel', 'Tableau']

In [ ]:
job_skills.pop(2)

'Tableau'

In [ ]:
job_skills

['SQL', 'Excel']

In [ ]:
kelly_skills = ['python', 'sql', 'looker']
luke_skills = ['python', 'bigquery', 'r']

all_skills = kelly_skills + luke_skills

all_skills

['python', 'sql', 'looker', 'python', 'bigquery', 'r']

In [ ]:
all_skills[::2]

['python', 'looker', 'bigquery']

In [ ]:
all_skills[-1:]

['r']

In [ ]:
all_skills[-2:]

['bigquery', 'r']

## Unpacking

Assign each value in an iterable to a variable in a single statement

In [ ]:
job_skills = ['python', 'excel', 'sql']

skill1, skill2, skill3 = job_skills

print(skill2)

excel

In [ ]:
job_skills = ['python', 'excel', 'sql', 'looker']

skill_concerned, *skill_dont_care = job_skills

print(skill_concerned)
print(skill_dont_care)

python
['excel', 'sql', 'looker']

### Lists, Dictionaries, Sets are Mutable Objects in Python

### Strings, Tuples, Integers are Immutable Objects in Python

## DICTIONARIES

In [ ]:
job_type_skills = {
    'database': 'postgres',
    'language': 'python',
    'library': 'pandas'
}

In [ ]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |
 |  Methods defined here:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __ior__(self, value, /)
 |      Return self|=value.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __reversed__(self, /)
 |      Return a reverse iterator over the dict keys.
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __setitem__(self, key, value, /)
 |      Set self[key] to value.
 |
 |  __sizeof__(self, /)
 |      Return the size of the dict in memory, in bytes.
 |
 |  clear(self, /)
 |      Remove all items from the dict.
 |
 |  copy(self, /)
 |      Return a shallow copy of the dict.
 |
 |  get(self, key, default=None, /)
 |      Return the value for key if key is in the dictionary, else default.
 |
 |  items(self, /)
 |      Return a set-like object providing a view on the dict's items.
 |
 |  keys(self, /)
 |      Return a set-like object providing a view on the dict's keys.
 |
 |  pop(self, key, default=<unrepresentable>, /)
 |      D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
 |
 |      If the key is not found, return the default if given; otherwise,
 |      raise a KeyError.
 |
 |  popitem(self, /)
 |      Remove and return a (key, value) pair as a 2-tuple.
 |
 |      Pairs are returned in LIFO (last-in, first-out) order.
 |      Raises KeyError if the dict is empty.
 |
 |  setdefault(self, key, default=None, /)
 |      Insert key with a value of default if key is not in the dictionary.
 |
 |      Return the value for key if key is in the dictionary, else default.
 |
 |  update(...)
 |      D.update([E, ]**F) -> None.  Update D from mapping/iterable E and F.
 |      If E is present and has a .keys() method, then does:  for k in E.keys(): D[k] = E[k]
 |      If E is present and lacks a .keys() method, then does:  for k, v in E: D[k] = v
 |      In either case, this is followed by: for k in F:  D[k] = F[k]
 |
 |  values(self, /)
 |      Return an object providing a view on the dict's values.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  __class_getitem__(object, /)
 |      dicts are generic over two types, signifying (respectively) the types of their keys and values
 |
 |  fromkeys(iterable, value=None, /)
 |      Create a new dictionary with keys from iterable and values set to value.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __hash__ = None

In [ ]:
job_type_skills['language']

'python'

In [ ]:
job_type_skills.keys()

dict_keys(['database', 'language', 'library'])

In [ ]:
job_type_skills.values()

dict_values(['postgres', 'python', 'pandas'])

In [ ]:
job_type_skills.pop('library')

'pandas'

In [ ]:
job_type_skills

{'database': 'postgres', 'language': 'python'}

In [ ]:
job_type_skills.update({'cloud': 'google cloud'})

In [ ]:
job_type_skills

{'database': 'postgres', 'language': 'python', 'cloud': 'google cloud'}

In [ ]:
job_type_skills['version control'] = 'git'

In [ ]:
job_type_skills

{'database': 'postgres',
 'language': 'python',
 'cloud': 'google cloud',
 'version control': 'git'}

## SETS

In [ ]:
job_skills = {'tableau', 'sql', 'python', 'statistics'}

job_skills

{'python', 'sql', 'statistics', 'tableau'}

In [ ]:
job_skills.add('looker')

job_skills

{'looker', 'python', 'sql', 'statistics', 'tableau'}

In [ ]:
job_skills.add('sql')

job_skills

{'looker', 'python', 'sql', 'statistics', 'tableau'}

In [ ]:
job_skills.pop() # removes a random item from the list

job_skills

{'looker', 'sql', 'statistics', 'tableau'}

In [ ]:
# job_skills.remove('tableau') # removes the specific item from the list

# job_skills

In [ ]:
# Example

skill_list = ['python', 'sql', 'statistics', 'tableau', 'python', 'sql', 'statistics', 'tableau']

In [ ]:
set(skill_list)

{'python', 'sql', 'statistics', 'tableau'}

In [ ]:
list(set(skill_list))

['python', 'sql', 'tableau', 'statistics']

## TUPLES

In [ ]:
lukes_skills = ('python', 'sql', 'statistics', 'tableau')

print(lukes_skills)

print(type(lukes_skills))

('python', 'sql', 'statistics', 'tableau')
<class 'tuple'>

In [ ]:
lukes_skills[3]

'tableau'

In [ ]:
lukes_skills[0:2]

('python', 'sql')

In [ ]:
new_skills = ('excel', 'power bi')

In [ ]:
lukes_skills + new_skills

('python', 'sql', 'statistics', 'tableau', 'excel', 'power bi')

In [ ]:
lukes_skills = ('python', 'sql', 'statistics', 'tableau')
print(id(lukes_skills))
new_skills = ('excel', 'power bi')

lukes_skills += new_skills
lukes_skills
print(id(lukes_skills))

# NOTE: the first lukes_skills variable and the second lukes_skills variable is not the same

132525876961312
132525878302400

In [ ]:
# Whereas, in case of lists (which are mutable objects):

lukes_skills = ['python', 'sql', 'statistics', 'tableau']
print(id(lukes_skills))
new_skills = ['excel', 'power bi']

lukes_skills += new_skills
lukes_skills
print(id(lukes_skills))

# both the lukes_skills variables are the same

132525877053760
132525877053760

## range()

In [ ]:
tuple(range(1, 101, 2))

(1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99)

## Membership Operators

1. in
2. not in

In [ ]:
'Data' in 'Data Nerd'

True

In [ ]:
job_skills = ['python', 'r', 'sql']

print('python' in job_skills)
print('sql' not in job_skills)

True
False

## == and is Operators

The core difference is that == compares values, while is compares identities

- == (Equality Operator): Checks if the data or contents of two objects are the same.
- is (Identity Operator): Checks if two variables point to the exact same memory location

In [ ]:
# Example
luke_salary = 100_000
kelly_salary = 100_000

print(luke_salary == kelly_salary)
print(luke_salary is kelly_salary)

True
False

In [ ]:
print(id(luke_salary))
print(id(kelly_salary))

132525877101328
132525877108016

In [ ]:
core_skills = ['python', 'sql', 'r']
lukes_skills = core_skills

print(core_skills is lukes_skills)

True

## LOOPS

### FOR LOOPS

In [ ]:
numbers = [0, 1, 2, 3, 4, 5]
for num in numbers:
  print(num)

0
1
2
3
4
5

In [ ]:
characters = 'PYTHON'
for char in characters:
  print(char)

P
Y
T
H
O
N

In [ ]:
years_experience = {
    'Luke':  3,
    'Kelly': 6,
    'Ken' :  4,
    'Alex':  3
}

In [ ]:
for person in years_experience:
  print(person)

Luke
Kelly
Ken
Alex

In [ ]:
for value in years_experience.values():
  print(value)

3
6
4
3

In [ ]:
for item in years_experience.items():
  print(item)

('Luke', 3)
('Kelly', 6)
('Ken', 4)
('Alex', 3)

In [ ]:
for key, value in years_experience.items():
  print(key, value)

Luke 3
Kelly 6
Ken 4
Alex 3

In [ ]:
# Check the applicants who have experience of more than 5 years

for (key, value) in years_experience.items():
  if (value > 5):
    print(key, 'has', value, 'years of experience')

Kelly has 6 years of experience

### WHILE LOOPS

In [ ]:
count = 1
while (count <= 5):
  print(count)
  count += 1

1
2
3
4
5

In [ ]:
# to print the first candidate with more than 5 years of experience

years_experience = {
    'Luke':  3,
    'Kelly': 6,
    'Ken' :  4,
    'Alex':  3,
    'Mary':  7
}

In [ ]:
years = 0
index = 0

years_list = list(years_experience.items())

while (years < 5):
  key, years = years_list[index]
  if (years >= 5):
    print(key, years)
  index += 1

Kelly 6

## LIST COMPREHENSION

In [ ]:
numbers = [x for x in range(101)]

numbers

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [ ]:
numbers = []

for num in range(101):
  numbers.append(num)

numbers

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [ ]:
numbers = [x*2 for x in range(101)]

numbers

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200]

In [ ]:
characters = [x for x in 'PYTHON']

characters

['P', 'Y', 'T', 'H', 'O', 'N']

## Exercise: Basics

In [ ]:
# Write a Python script to find out what jobs you are qualified based on a set of skills.

my_skills = ['Python', 'SQL', 'Excel']

job_roles = [
    {'role': 'Data Analyst', 'skills': ['Python', 'SQL', 'Excel']},
    {'role': 'Data Scientist', 'skills': ['Python', 'R', 'Machine Learning', 'Deep Learning']},
    {'role': 'Machine Learning Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn']},
    {'role': 'Data Engineer', 'skills': ['Python', 'Apache Spark', 'Hadoop', 'SQL']},
    {'role': 'Business Intelligence Analyst', 'skills': ['Python', 'SQL', 'Tableau', 'Power BI', 'Excel']},
    {'role': 'Quantitative Analyst', 'skills': ['R', 'Python', 'MATLAB', 'Statistics']},
    {'role': 'Operations Analyst', 'skills': ['Python', 'SQL', 'Data Visualization', 'Process Improvement']},
    {'role': 'Database Administrator', 'skills': ['SQL', 'Oracle', 'MySQL', 'Database Management']},
    {'role': 'AI Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision']},
    {'role': 'Statistician', 'skills': ['R', 'SAS', 'Python', 'Statistical Modeling']}
]

In [ ]:
# Method-1:

for job in job_roles:
  if ('Python' in job['skills']) and ('SQL' in job['skills']) and ('Excel' in job['skills']):
    print(job['role'])

Data Analyst
Business Intelligence Analyst

In [ ]:
# Method-2:

for job in job_roles:
  required_skills = job['skills']

  if (set(my_skills).issubset(required_skills)):
    print(job['role'])

Data Analyst
Business Intelligence Analyst

In [ ]:
# Method-3:

for job in job_roles:
  qualified = True

  for skill in my_skills:
    if(skill not in job['skills']):
      qualified = False

  if qualified:
    print(job['role'])

Data Analyst
Business Intelligence Analyst

In [ ]:
# Method-3:

qualified_roles = []

for job in job_roles:
  qualified = True

  for skill in my_skills:
    if(skill not in job['skills']):
      qualified = False

  if qualified:
    qualified_roles.append(job['role'])

qualified_roles

['Data Analyst', 'Business Intelligence Analyst']

# Built-In Functions

In [ ]:
data_salaries = [95000, 100000, 85000, 97000, 140000]

In [ ]:
min(data_salaries)

85000

In [ ]:
max(data_salaries)

140000

In [ ]:
sum(data_salaries)

517000

In [ ]:
sorted(data_salaries)

[85000, 95000, 97000, 100000, 140000]

# User-Defined Functions

In [ ]:
base_salary = 100000
bonus_rate = 0.1

# total_salary = base_salary * (1 + bonus_rate)

In [ ]:
# Calculating the total salary using a user-defined function

def total_salary(base, bonus):
  return base * (1 + bonus)

print(total_salary(100000, 0.1))

110000.00000000001

In [ ]:
# If any of the function parameters are to be kept constant for every test case, define the same in the function definition
# No need to call the

def total_salary(base, bonus = .5):
  return base * (1 + bonus)

print(total_salary(100000))

150000.0

# Lambda Functions

A small, anonymous function that is defined without a name. Unlike standard functions created using the 'def' keyword, lambda functions are written in a single line and are typically used for quick, one-time operations.

In [ ]:
mul_two = lambda x: x * 2
mul_two(3)

6

In [ ]:
(lambda x: x * 2)(3)

6

In [ ]:
(lambda x, y: x * 2 + y)(3, 4)

10

In [ ]:
# Calculating the bonus-added salaries using list comprehension

salary_list = [100000, 200000, 150000, 120000, 80000, 750000]

def calculate_salary(base, bonus = 0.1):
  return base * (1 + bonus)

bonus_salary = [calculate_salary(salary) for salary in salary_list]
bonus_salary

[110000.00000000001,
 220000.00000000003,
 165000.0,
 132000.0,
 88000.0,
 825000.0000000001]

In [ ]:
# Defining the above process using lambda function

salary_list = [100000, 200000, 150000, 120000, 80000, 750000]

def calculate_salary(base, bonus = 0.1):
  return base * (1 + bonus)

bonus_salary = [(lambda x: x * 1.1)(salary) for salary in salary_list]
bonus_salary

[110000.00000000001,
 220000.00000000003,
 165000.0,
 132000.0,
 88000.0,
 825000.0000000001]

### Data Filtering Example

Find jobs that have Python and that are remote

In [ ]:
job_data = [
    {'job_title': 'Data Scientist', 'job_skills': ['Python', 'Machine Learning'], 'remote': True},
    {'job_title': 'Data Analyst', 'job_skills': ['Excel', 'SQL'], 'remote': False},
    {'job_title': 'Machine Learning Engineer', 'job_skills': ['Python', 'TensorFlow', 'Keras'], 'remote': True},
    {'job_title': 'Software Developer', 'job_skills': ['Java', 'C++'], 'remote': True},
    {'job_title': 'Data Scientist', 'job_skills': ['R', 'Statistics'], 'remote': False},
]

In [ ]:
help(filter)

Help on class filter in module builtins:

class filter(object)
 |  filter(function, iterable, /)
 |
 |  Return an iterator yielding those items of iterable for which
 |  function(item) is true.  If function is None, return the items that
 |  are true.
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __next__(self, /)
 |      Implement next(self).
 |
 |  __reduce__(self, /)
 |      Return state information for pickling.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.

In [ ]:
# Filtering jobs that are rmeote

list(filter(lambda job: job['remote'], job_data))

[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'Machine Learning'],
  'remote': True},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Keras'],
  'remote': True},
 {'job_title': 'Software Developer',
  'job_skills': ['Java', 'C++'],
  'remote': True}]

In [ ]:
# Also filtering jobs that have Python

list(filter(lambda job: job['remote'] and 'Python' in job['job_skills'], job_data))

[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'Machine Learning'],
  'remote': True},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Keras'],
  'remote': True}]

# Python Standard Library

## Modules

In [ ]:
# import my_module

In [ ]:
# # To print something from your module
# my_module.my_skills

In [ ]:
# my_module.skill('Python')

In [ ]:
# # New Module

# import job_analyzer

In [ ]:
# job_analyzer.calculate_salary(100000)

In [ ]:
# # Another method to define a module

# from job_analyzer import calculate_salary, calculate_bonus

# calculate_salary(100000)

# calculate_bonus(110000, 100000)

In [ ]:
# # To import all the functions from the module, use a (*) star notation

# from job_analyzer import *

In [ ]:
# help(calculate_salary)

## Statistics Module

In [ ]:
salary_list = [98000, 101000, 102000, 99000, 97000]

In [ ]:
from statistics import mean, median, mode

print(mean(salary_list))
print(median(salary_list))
print(mode(salary_list))

99400
99000
98000

## Exercise: Data CLeaning

Cleanup list and datetime objects

- Make the job_date column's datatype 'datetime' from 'str'
- Make the job_skills column's datatype 'list' from 'str'

In [ ]:
data_science_jobs = [
    {'job_title': 'Data Scientist', 'job_skills': "['Python', 'SQL', 'Machine Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Machine Learning Engineer', 'job_skills': "['Python', 'TensorFlow', 'Deep Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Data Analyst', 'job_skills': "['SQL', 'R', 'Tableau']", 'job_date': '2023-05-10'},
    {'job_title': 'Business Intelligence Developer', 'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']", 'job_date': '2023-05-12'},
    {'job_title': 'Data Engineer', 'job_skills': "['Python', 'Spark', 'Hadoop']", 'job_date': '2023-05-18'},
    {'job_title': 'AI Specialist', 'job_skills': "['Python', 'PyTorch', 'AI Ethics']", 'job_date': '2023-05-20'},
]

In [ ]:
from datetime import datetime

datetime.now()

datetime.datetime(2026, 9, 24, 15, 56, 28, 251480)

In [ ]:
data_science_jobs[0]['job_date']

'2023-05-12'

In [ ]:
type(data_science_jobs[0]['job_date'])

str

In [ ]:
test_date = data_science_jobs[0]['job_date']

# strptime() -> string parse time
print(datetime.strptime(test_date, '%Y-%m-%d'))

2023-05-12 00:00:00

In [ ]:
for job in data_science_jobs:
  job['job_date'] = datetime.strptime(job['job_date'], '%Y-%m-%d')

data_science_jobs

[{'job_title': 'Data Scientist',
  'job_skills': "['Python', 'SQL', 'Machine Learning']",
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': "['Python', 'TensorFlow', 'Deep Learning']",
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Data Analyst',
  'job_skills': "['SQL', 'R', 'Tableau']",
  'job_date': datetime.datetime(2023, 5, 10, 0, 0)},
 {'job_title': 'Business Intelligence Developer',
  'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']",
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Data Engineer',
  'job_skills': "['Python', 'Spark', 'Hadoop']",
  'job_date': datetime.datetime(2023, 5, 18, 0, 0)},
 {'job_title': 'AI Specialist',
  'job_skills': "['Python', 'PyTorch', 'AI Ethics']",
  'job_date': datetime.datetime(2023, 5, 20, 0, 0)}]

In [ ]:
type(data_science_jobs[0]['job_skills'])

str

In [ ]:
# ast -> abstract syntax trees
import ast

for job in data_science_jobs:
  job['job_skills'] = ast.literal_eval(job['job_skills'])

In [ ]:
data_science_jobs

[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'SQL', 'Machine Learning'],
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Deep Learning'],
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Data Analyst',
  'job_skills': ['SQL', 'R', 'Tableau'],
  'job_date': datetime.datetime(2023, 5, 10, 0, 0)},
 {'job_title': 'Business Intelligence Developer',
  'job_skills': ['SQL', 'PowerBI', 'Data Warehousing'],
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Data Engineer',
  'job_skills': ['Python', 'Spark', 'Hadoop'],
  'job_date': datetime.datetime(2023, 5, 18, 0, 0)},
 {'job_title': 'AI Specialist',
  'job_skills': ['Python', 'PyTorch', 'AI Ethics'],
  'job_date': datetime.datetime(2023, 5, 20, 0, 0)}]

In [ ]:
file = open('sample_data/california_housing_test.csv')
content = file.read()
file.close()

## Pandas

In [ ]:
import pandas as pd

contents_1 = pd.read_csv('sample_data/california_housing_test.csv')

contents_1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
contents_1['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
print(contents_1['total_bedrooms'].sum())

1589852.0

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip list

Package                               Version
------------------------------------- ------------------
absl-py                               1.4.0
accelerate                            1.14.0
access                                1.1.10.post3
affine                                3.0.1
aiofiles                              25.1.0
aiohappyeyeballs                      2.7.1
aiohttp                               3.14.3
aiosignal                             1.4.0
aiosqlite                             0.22.1
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.12.1
altair                                5.5.0
annotated-doc                         0.0.5
annotated-types                       0.8.0
antlr4-python3-runtime                4.9.3
anyio                                 4.14.2
anywidget                             0.9.21
apsw                                  3.53.4.0
argon2-cffi                           25.1.0
argon2-cffi-bindings                  26.1.0
array_record                          0.8.3
arrow                                 1.4.0
arviz                                 0.22.0
astropy                               7.2.2
astropy-iers-data                     0.2026.8.31.0.57.9
astunparse                            1.6.3
atpublic                              5.1
attrs                                 26.1.0
audioop-lts                           0.2.2
audioread                             3.1.0
Authlib                               1.8.0
autograd                              1.9.1
babel                                 2.18.0
backcall                              0.2.0
beartype                              0.22.9
beautifulsoup4                        4.13.5
betterproto                           2.0.0b7
bigframes                             2.48.0
bigquery-magics                       0.14.0
bleach                                6.4.0
blinker                               1.9.0
blis                                  1.3.3
blobfile                              3.3.0
blosc2                                4.12.0
bokeh                                 3.8.2
Bottleneck                            1.4.2
bqplot                                0.12.47
branca                                0.8.2
brotli                                1.2.0
CacheControl                          0.14.4
cachetools                            6.2.6
catalogue                             2.0.10
certifi                               2026.7.22
cffi                                  2.1.1
chardet                               5.2.0
charset-normalizer                    3.4.9
clarabel                              0.11.1
click                                 8.5.0
cligj                                 0.7.2
cloudpathlib                          0.25.0
cloudpickle                           3.1.2
cmake                                 3.31.10
cmdstanpy                             1.3.0
colorcet                              3.2.1
colorlover                            0.3.0
community                             1.0.0b1
confection                            1.3.3
cons                                  0.4.7
contourpy                             1.3.3
cramjam                               2.12.1
cryptography                          50.0.1
cufflinks                             0.17.3
curl_cffi                             0.16.2
cvxopt                                1.3.2
cvxpy                                 1.6.7
cycler                                0.12.1
cyipopt                               1.5.0
cymem                                 2.0.13
Cython                                3.0.12
dask                                  2026.8.0
dataproc-spark-connect                1.1.0
datasets                              4.8.5
db-dtypes                             1.7.1
dbus-python                           1.3.2
debugpy                               1.8.15
decorator                             4.4.2
defusedxml                            0.7.1
deprecation                           2.1.0
diffusers                             0.40.0
dill                                  0.4.1
distro                                1.9.0
dlib                                  19.24.6
dm-tree                               0.1.10
docstring_parser                      0.18.0
docutils                              0.21.2
dopamine_rl                           4.1.2
duckdb                                1.3.2
earthengine-api                       1.7.39
easydict                              1.13
editdistance                          0.8.1
eerepr                                0.1.2
einops                                0.8.2
en_core_web_sm                        3.8.0
entrypoints                           0.4
esda                                  2.9.0
et_xmlfile                            2.0.0
etils                                 1.14.0
etuples                               0.3.10
Farama-Notifications                  0.0.6
fastai                                2.8.8
fastapi                               0.141.1
fastcore                              2.2.19
fastdownload                          0.0.7
fastjsonschema                        2.22.2
fastprogress                          1.1.6
fasttransform                         0.0.2
filelock                              3.32.5
firebase-admin                        6.9.0
Flask                                 3.1.3
flatbuffers                           25.12.19
flax                                  0.11.2
folium                                0.20.0
fonttools                             4.64.0
formulaic                             1.2.2
fqdn                                  1.5.1
frozendict                            2.4.7
frozenlist                            1.8.0
fsspec                                2025.12.0
future                                1.0.0
gast                                  0.7.0
gcsfs                                 2025.12.0
GDAL                                  3.8.4
gdown                                 5.2.2
geemap                                0.38.4
geocoder                              1.38.1
geographiclib                         2.1
geopandas                             1.1.4
geopy                                 2.4.1
giddy                                 2.3.9
gin-config                            0.5.0
glob2                                 0.7
google                                3.0.0
google-adk                            2.7.1
google-ai-generativelanguage          0.6.15
google-api-core                       2.30.3
google-api-python-client              2.200.0
google-auth                           2.49.0
google-auth-httplib2                  0.4.2
google-auth-oauthlib                  1.4.1
google-cloud-bigquery                 3.44.0
google-cloud-bigquery-connection      1.22.0
google-cloud-bigquery-storage         2.39.0
google-cloud-core                     2.7.0
google-cloud-dataproc                 5.28.0
google-cloud-datastore                2.25.0
google-cloud-firestore                2.27.0
google-cloud-functions                1.24.0
google-cloud-language                 2.21.0
google-cloud-monitoring               2.31.0
google-cloud-resource-manager         1.18.0
google-cloud-spanner                  3.68.0
google-cloud-storage                  3.13.1
google-cloud-storage-control          1.12.0
google-cloud-translate                3.27.0
google-colab                          1.0.0
google-crc32c                         1.8.0
google-genai                          2.12.1
google-generativeai                   0.8.6
google-pasta                          0.2.0
google-resumable-media                2.10.2
googleapis-common-protos              1.75.0
googledrivedownloader                 1.1.0
gradio                                6.26.0
gradio_client                         2.6.1
grain                                 0.2.18
graphviz                              0.21
greenlet                              3.5.5
groovy                                0.1.2
grpc-google-iam-v1                    0.14.4
grpc-interceptor                      0.15.4
grpcio                                1.83.1
grpcio-status                         1.71.2
grpclib                               0.4.9
gspread                               6.2.1
gspread-dataframe                     4.0.0
gym                                   0.25.2
gym-notices                           0.1.0
gymnasium                             1.3.0
h11                                   0.16.0
h2                                    4.4.1
h5netcdf                              1.8.1
h5py                                  3.16.0
hdbscan                               0.8.44
hf-gradio                             0.4.1
hf-xet                                1.6.0
highspy                               1.15.1
holidays                              0.103
holoviews                             1.23.2
hpack                                 4.2.0
html5lib                              1.1
httpcore                              1.0.9
httpcore2                             2.12.0
httpimport                            1.4.1
httplib2                              0.32.0
httptools                             0.8.0
httpx                                 0.28.1
httpx2                                2.12.0
huggingface_hub                       1.29.0
humanize                              4.16.0
hyperframe                            6.1.0
hyperopt                              0.3.0
ibis-framework                        9.5.0
idna                                  3.19
ImageIO                               2.37.4
imageio-ffmpeg                        0.6.0
imagesize                             2.0.1
imbalanced-learn                      0.14.2
immutabledict                         4.3.1
importlib_metadata                    9.0.1
imutils                               0.5.4
inequality                            1.1.2
inflect                               7.5.0
iniconfig                             2.3.0
intel-cmplr-lib-ur                    2025.3.3
intel-openmp                          2025.3.3
interface_meta                        2.0.1
ipyevents                             2.0.4
ipyfilechooser                        0.6.0
ipykernel                             6.17.1
ipyleaflet                            0.20.0
ipyparallel                           8.8.0
ipython                               7.34.0
ipython-genutils                      0.2.0
ipython-sql                           0.5.0
ipywidgets                            7.7.1
isoduration                           20.11.0
itsdangerous                          2.2.0
jaraco.classes                        3.4.0
jaraco.context                        6.1.2
jaraco.functools                      4.6.0
jax                                   0.11.1
jaxlib                                0.11.1
jeepney                               0.9.0
jieba                                 0.42.1
Jinja2                                3.1.6
jiter                                 0.16.0
joblib                                1.6.0
joserfc                               1.7.5
jsonpatch                             1.33
jsonpickle                            4.1.2
jsonpointer                           3.1.1
jsonschema                            4.26.0
jsonschema-specifications             2025.9.1
jupyter_client                        7.4.9
jupyter-console                       6.6.3
jupyter_core                          5.9.1
jupyter-events                        0.12.1
jupyter_kernel_gateway                2.5.2
jupyter-leaflet                       0.20.0
jupyter_server                        2.20.0
jupyter_server_terminals              0.5.4
jupyterlab_pygments                   0.3.0
jupyterlab_widgets                    3.0.17
jupytext                              1.19.5
kaggle                                2.0.2
kagglehub                             1.0.2
kagglesdk                             0.1.37
keras                                 3.13.2
keras-hub                             0.26.0
keras-nlp                             0.26.0
keyring                               25.7.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.5.1
langchain                             1.3.18
langchain-core                        1.6.1
langchain-protocol                    0.0.19
langgraph                             1.2.11
langgraph-checkpoint                  4.2.0
langgraph-prebuilt                    1.1.0
langgraph-sdk                         0.4.4
langsmith                             0.12.1
lark                                  1.3.1
launchpadlib                          1.11.0
lazr.restfulclient                    0.14.6
lazr.uri                              1.0.6
lazy-loader                           0.5
libclang                              18.1.1
libpysal                              4.14.1
librosa                               0.11.0
lightgbm                              4.6.0
linkify-it-py                         2.2.0
llvmlite                              0.44.0
locket                                1.0.0
logical-unification                   0.4.7
lxml                                  6.1.2
Mako                                  1.3.2.dev0
mapclassify                           2.10.0
Markdown                              3.10.3
markdown-it-py                        4.2.0
MarkupSafe                            3.0.3
matplotlib                            3.10.0
matplotlib-inline                     0.2.2
matplotlib-venn                       1.1.2
mdit-py-plugins                       0.6.1
mdurl                                 0.1.2
mgwr                                  2.2.1
miniKanren                            1.0.5
missingno                             0.5.2
mistune                               3.3.4
mizani                                0.13.5
mkl                                   2025.3.1
ml_dtypes                             0.6.0
mlxtend                               0.23.4
mmh3                                  5.3.0
momepy                                0.11.0
more-itertools                        10.8.0
moviepy                               1.0.3
mpmath                                1.3.0
msgpack                               1.2.2
multidict                             6.7.1
multipledispatch                      1.0.0
multiprocess                          0.70.19
multitasking                          0.0.13
murmurhash                            1.0.15
music21                               9.9.2
namex                                 0.1.0
narwhals                              2.25.0
natsort                               8.4.0
nbclassic                             1.3.3
nbclient                              0.10.4
nbconvert                             7.17.1
nbformat                              5.11.1
ndindex                               1.10.1
nest-asyncio                          1.6.0
networkx                              3.6.1
nh3                                   0.3.7
nibabel                               5.4.2
nltk                                  3.9.1
notebook                              6.5.7
notebook_shim                         0.2.4
numba                                 0.61.2
numexpr                               2.14.2
numpy                                 2.1.3
nvidia-nccl-cu13                      2.31.2
oauth2client                          4.1.3
oauthlib                              3.3.1
omegaconf                             2.3.1
onemkl-license                        2025.3.1
openai                                2.54.0
opencv-contrib-python                 4.14.0.94
opencv-python                         5.0.0.93
opencv-python-headless                5.0.0.93
openpyxl                              3.1.5
opentelemetry-api                     1.42.1
opentelemetry-resourcedetector-gcp    1.14.0
opentelemetry-sdk                     1.42.1
opentelemetry-semantic-conventions    0.63b1
opt_einsum                            3.4.0
optax                                 0.2.8
optree                                0.20.0
orbax-checkpoint                      0.12.4
orjson                                3.12.0
ormsgpack                             1.12.2
osqp                                  1.1.3
packaging                             26.3
pandas                                2.2.3
pandas-datareader                     0.11.1
pandas-gbq                            0.30.0
pandas-stubs                          2.2.3.250527
pandocfilters                         1.5.1
panel                                 1.9.4
panel-material-ui                     0.14.2
param                                 2.4.1
parso                                 0.8.7
parsy                                 2.2
partd                                 1.4.2
patsy                                 1.0.3
peewee                                4.4.0
peft                                  0.20.0
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                11.3.0
pip                                   24.1.2
platformdirs                          4.11.7
plotly                                5.24.1
plotnine                              0.14.5
pluggy                                1.6.0
plum-dispatch                         2.9.0
pointpats                             2.5.5
polars                                1.35.2
polars-runtime-32                     1.35.2
pooch                                 1.9.0
portpicker                            1.5.2
preshed                               3.0.13
prettytable                           3.18.0
proglog                               0.1.12
progressbar2                          4.5.0
prometheus_client                     0.26.0
promise                               2.3
prompt_toolkit                        3.0.53
propcache                             0.5.2
prophet                               1.4.0
proto-plus                            1.28.2
protobuf                              5.29.6
psutil                                5.9.5
psycopg2                              2.9.12
psygnal                               0.15.1
ptyprocess                            0.7.0
PuLP                                  3.3.2
py-cpuinfo                            9.0.0
py4j                                  0.10.9.9
pyarrow                               23.0.1
pyasn1                                0.6.4
pyasn1_modules                        0.4.2
pycairo                               1.29.1
pycocotools                           2.0.11
pycparser                             3.0
pycryptodomex                         3.23.0
pydantic                              2.13.5
pydantic_core                         2.46.5
pydata-google-auth                    1.9.1
pydot                                 4.0.1
pydotplus                             2.0.2
PyDrive2                              1.21.1
pydub                                 0.25.1
pyerfa                                2.0.1.5
pygame                                2.6.1
pygit2                                1.20.0
Pygments                              2.21.0
PyGObject                             3.48.2
pyiceberg                             0.12.0
PyJWT                                 2.13.0
pymc                                  5.28.5
pynndescent                           0.6.0
pyogrio                               0.13.0
pyomo                                 6.10.1
PyOpenGL                              3.1.10
pyOpenSSL                             26.4.0
pyparsing                             3.3.2
pyperclip                             1.11.0
pyproj                                3.7.2
pyroaring                             1.1.0
pysal                                 25.7
pyshp                                 3.1.6

In [ ]:
!pip install pyjokes

Collecting pyjokes
  Downloading pyjokes-0.8.3-py3-none-any.whl.metadata (3.4 kB)
Downloading pyjokes-0.8.3-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 kB 1.5 MB/s eta 0:00:00
Installing collected packages: pyjokes
Successfully installed pyjokes-0.8.3

In [ ]:
import pyjokes

In [ ]:
help(pyjokes)

Help on package pyjokes:

NAME
    pyjokes

PACKAGE CONTENTS
    cli (package)
    exc
    jokes_cs
    jokes_de
    jokes_en
    jokes_es
    jokes_eu
    jokes_fr
    jokes_gl
    jokes_hu
    jokes_it
    jokes_lt
    jokes_pl
    jokes_ru
    jokes_sv
    pyjokes

DATA
    CATEGORY_VALUES = {'all', 'chuck', 'neutral'}
    LANGUAGE_VALUES = {'cs', 'de', 'en', 'es', 'eu', 'fr', ...}

FILE
    /usr/local/lib/python3.13/dist-packages/pyjokes/__init__.py

In [ ]:
pyjokes.get_joke()

'Bugs come in through open Windows.'

In [ ]:
pyjokes.get_jokes()

["Complaining about the lack of smoking shelters, the nicotine addicted Python programmers said there ought to be 'spaces for tabs'.",
 'Ubuntu users are apt to get this joke.',
 'Obfuscated Reality Mappers (ORMs) can be useful database tools.',
 'Asked to explain Unicode during an interview, Geoff went into detail about his final year university project. He was not hired.',
 "Triumphantly, Beth removed Python 2.7 from her server in 2030. 'Finally!' she said with glee, only to see the announcement for Python 4.4.",
 "An SQL query goes into a bar, walks up to two tables and asks, 'Can I join you?'",
 'When your hammer is C++, everything begins to look like a thumb.',
 'If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl.',
 'To understand recursion you must first understand recursion.',
 "I suggested holding a 'Python Object Oriented Programming Seminar', but the acronym was unpopular.",
 "'Knock, knock.' 'Who's there?' ... very long pause ... 'Java.'",
 "How many programmers does it take to change a lightbulb? None, that's a hardware problem.",
 "What's the object-oriented way to become wealthy? Inheritance.",
 "Why don't jokes work in octal? Because 7 10 11.",
 'How many programmers does it take to change a lightbulb? None, they just make darkness a standard.',
 "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
 "Two threads walk into a bar. The barkeeper looks up and yells, 'Hey, I want don't any conditions race like time last!'",
 "Old C programmers don't die, they're just cast into void.",
 "Eight bytes walk into a bar. The bartender asks, 'Can I get you anything?' 'Yeah,' replies the bytes. 'Make us a double.'",
 "Why did the programmer quit his job? Because he didn't get arrays.",
 "Why do Java programmers have to wear glasses? Because they don't see sharp.",
 'Software developers like to solve problems. If there are no problems handily available, they will create their own.',
 ".NET was named .NET so that it wouldn't show up in a Unix directory listing.",
 'Hardware: The part of a computer that you can kick.',
 "A programmer was found dead in the shower. Next to their body was a bottle of shampoo with the instructions 'Lather, Rinse and Repeat'.",
 'Optimist: The glass is half full. Pessimist: The glass is half empty. Programmer: The glass is twice as large as necessary.',
 'In C we had to code our own bugs. In C++ we can inherit them.',
 'How come there is no obfuscated Perl contest? Because everyone would win.',
 "If you play a Windows CD backwards, you'll hear satanic chanting ... worse still, if you play it forwards, it installs Windows.",
 'How many programmers does it take to kill a cockroach? Two: one holds, the other installs Windows on it.',
 'What do you call a programmer from Finland? Nerdic.',
 "What did the Java code say to the C code? A: You've got no class.",
 "Why did Microsoft name their search engine BING? Because It's Not Google.",
 "Pirates go 'arg!', computer pirates go 'argv!'",
 'Software salesmen and used-car salesmen differ in that the latter know when they are lying.',
 "Child: Dad, why does the sun rise in the east and set in the west? Dad: Son, it's working, don't touch it.",
 'Why do programmers confuse Halloween with Christmas? Because OCT 31 == DEC 25.',
 'How many Prolog programmers does it take to change a lightbulb? false.',
 'Real programmers can write assembly code in any language.',
 'Waiter: Would you like coffee or tea? Programmer: Yes.',
 'What do you get when you cross a cat and a dog? Cat dog sin theta.',
 "If loving you is ROM I don't wanna read write.",
 'A programmer walks into a foo...',
 "A programmer walks into a bar and orders 1.38 root beers. The bartender informs her it's a root beer float. She says 'Make it a double!'",
 "What is Benoit B. Mandelbrot's middle name? Benoit B. Mandelbrot.",
 "Why are you always smiling? That's just my... regular expression.",
 'ASCII stupid question, get a stupid ANSI.',
 "A programmer had a problem. He thought to himself, 'I know, I'll solve it with threads!'. has Now problems. two he",
 'Why do sin and tan work? Just cos.',
 'Java: Write once, run away.',
 'I would tell you a joke about UDP, but you would never get it.',
 'A QA engineer walks into a bar. Runs into a bar. Crawls into a bar. Dances into a bar. Tiptoes into a bar. Rams a bar. Jumps into a bar.',
 "My friend's in a band called '1023 Megabytes'... They haven't got a gig yet!",
 "I had a problem so I thought I'd use Java. Now I have a ProblemFactory.",
 'QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.',
 'A product manager walks into a bar, asks for drink. Bartender says no, but will consider adding later.',
 'How do you generate a random string? Put a first year Computer Science student in Vim and ask them to save and exit.',
 "I've been using Vim for a long time now, mainly because I can't figure out how to exit.",
 "How do you know whether a person is a Vim user? Don't worry, they'll tell you.",
 "Waiter: He's choking! Is anyone a doctor? Programmer: I'm a Vim user.",
 "3 Database Admins walked into a NoSQL bar. A little while later they walked out because they couldn't find a table.",
 'How to explain the movie Inception to a programmer? When you run a VM inside another VM, inside another VM ... everything runs real slow!',
 'What do you call a parrot that says "Squawk! Pieces of nine! Pieces of nine!"? A parrot-ey error.',
 'There are only two hard problems in Computer Science: cache invalidation, naming things and off-by-one-errors.',
 "There are 10 types of people: those who understand binary and those who don't.",
 'There are 2 types of people: those who can extrapolate from incomplete data sets...',
 "There are II types of people: Those who understand Roman Numerals and those who don't.",
 'There are 10 types of people: those who understand hexadecimal and 15 others.',
 "There are 10 types of people: those who understand binary, those who don't, and those who were expecting this joke to be in trinary.",
 "There are 10 types of people: those who understand trinary, those who don't, and those who have never heard of it.",
 'What do you call eight hobbits? A hobbyte.',
 'The best thing about a Boolean is even if you are wrong, you are only off by a bit.',
 'A good programmer is someone who always looks both ways before crossing a one-way street.',
 'There are two ways to write error-free programs; only the third one works.',
 'QAs consist of 55% water, 30% blood and 15% Jira tickets.',
 'Sympathy for the Devil is really just about being nice to QAs.',
 "How many QAs does it take to change a lightbulb? They noticed that the room was dark. They don't fix problems, they find them.",
 'A programmer crashes a car at the bottom of a hill, a bystander asks what happened, he says "No idea. Let\'s push it back up and try again".',
 "What do you mean 911 is only for emergencies? I've got a merge conflict.",
 "Writing PHP is like peeing in the swimming pool, everyone did it, but we don't need to bring it up in public.",
 "Why did the QA cross the road? To ruin everyone's day.",
 'Number of days since I have encountered an array index error: -1.',
 'Number of days since I have encountered an off-by-one error: 0.',
 'Speed dating is useless. 5 minutes is not enough to properly explain the benefits of the Unix philosophy.',
 'Microsoft hold a bi-monthly internal "productive week" where they use Google instead of Bing.',
 "Schrodinger's attitude to web development: If I don't look at it in Internet Explorer then there's a chance it looks fine.",
 'Finding a good PHP developer is like looking for a needle in a haystack. Or is it a hackstack in a needle?',
 "Unix is user friendly. It's just very particular about who its friends are.",
 'A COBOL programmer makes millions with Y2K remediation and decides to get cryogenically frozen. "The year is 9999. You know COBOL, right?"',
 'The C language combines all the power of assembly language with all the ease-of-use of assembly language.',
 'An SEO expert walks into a bar, bars, pub, public house, Irish pub, tavern, bartender, beer, liquor, wine, alcohol, spirits...',
 "What does 'Emacs' stand for? 'Exclusively used by middle aged computer scientists.'",
 'What does pyjokes have in common with Adobe Flash? It gets updated all the time, but never gets any better.',
 "Why does Waldo only wear stripes? Because he doesn't want to be spotted.",
 'I went to a street where the houses were numbered 8k, 16k, 32k, 64k, 128k, 256k and 512k. It was a trip down Memory Lane.',
 "!false, (It's funny because it's true)",
 "['hip', 'hip'] (hip hip array!)",
 "Programmer: The ship I boarded crashed and I am dying! Project Manager: Then let's do a quick knowledge transfer session before you go.",
 'Are you a RESTful API? because you GET my attention, PUT some love, POST the cutest smile, and DELETE my bad day.',
 'I used to know a joke about Java, but I run out of memory.',
 'My girlfriend dumped me after I named a class after her. She felt I treated her like an object.',
 'Girl: Do you drink? Programmer: No. Girl: Have Girlfriend? Programmer: No. Girl: Then how do you enjoy life? Programmer: I am Programmer',
 'A Programmer was walking out of door for work, his wife said "while you\'re out, buy some milk" and he never returned.',
 'A: What is your address? Me: 173.168.15.10 A: No, your local address Me: 127.0.0.1 A: I mean your physical address B: 29:01:38:62:31:58',
 'Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.',
 'Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.',
 'There are three kinds of lies: Lies, damned lies, and benchmarks.',
 'All programmers are playwrights, and all computers are lousy actors.',
 "Have you heard about the new Cray super computer? It's so fast, it executes an infinite loop in 6 seconds.",
 'The generation of random numbers is too important to be left to chance.',
 'I just saw my life flash before my eyes and all I could see was a close tag.',
 'The computer is mightier than the pen, the sword, and usually, the programmer',
 'Debugging: Removing the needles from the haystack.',
 'If doctors were like software engineers, they would say things like Have you tried killing yourself and being reborn?',
 'Debugging is like being the detective in a crime drama where you are also the murderer.',
 'The best thing about a Boolean is that even if you are wrong, you are only off by a bit.',
 'If you listen to a UNIX shell, can you hear the C?',
 "Why do Java programmers have to wear glasses? Because they don't C#.",
 'When Apple employees die, does their life HTML5 in front of their eyes?',
 'What did the router say to the doctor? It hurts when IP.',
 'Learning JavaScript is like looking both ways before you cross the street, and then getting hit by an airplane.',
 'I for one am excited for the days when dereferencing a null pointer causes an aneurysm.',
 'Debugging is like an onion. There are multiple layers to it, and the more you peel them back.',
 "When your code does not change color automatically, Something's wrong, I can feel it.",
 'I have a joke on programming but it only works on my computer.',
 "Why do you always use i and j variales in loops? It's the law......",
 'As far as we know, our computer has never had an undetected error.',
 'A user friendly computer first requires a friendly user.',
 "Bug? That's not a bug, that's a feature.",
 'Buy a Pentium 586/200 so you can reboot faster.',
 "Computer analyst to programmer: You start coding. I'll go find out what they want.",
 'Computer programmers do it byte by byte.',
 "Don't compute and drive; the life you save may be your own.",
 'How an engineer writes a program: Start by debugging an empty file...',
 "If at first you don't succeed, call it version 1.0.",
 'I have a dream: 1073741824 bytes free.',
 "I haven't lost my mind; it's backed up on tape somewhere.",
 'Is reading in the bathroom considered Multi-Tasking.',
 "Never say 'OOPS!' always say 'Ah, Interesting!'",
 "One person's error is another person's data.",
 'Press CTRL-ALT-DEL to continue....',
 "Programmer's Time-Space Continuum: Programmers continuously space the time.",
 'Speed Kills! Use Windows.',
 "The box said: 'install on Windows 95, NT 4.0 or better'. So I installed it on Linux.",
 'The program is absolutely right; therefore the computer must be wrong.',
 "There are only 10 types of people in this world: those who understand binary, and those who don't.",
 'There were computers in Biblical times. Eve had an Apple.',
 'Those who can, do. Those who cannot, teach. Those who cannot teach, HACK!',
 'User error: replace user and press any key to continue.',
 'Warning, keyboard not found. Press Enter to continue.',
 "Why do they call this a word processor? It's simple, ... you've seen what food processors do to food, right?",
 'Why do we want intelligent terminals when there are so many stupid users?',
 'Windows is NOT a virus. Viruses DO something.',
 'WINDOWS stands for Will Install Needless Data On Whole System.',
 'You are making progress if each mistake is a new one.',
 'You had mail, but the super-user read it, and deleted it!',
 'You never finish a program, you just stop working on it.',
 "You don't have to know how the computer works, just how to work the computer.",
 "You forgot to do your backup 16 days ago. Tomorrow you'll need that version.",
 "I love pressing the F5 key. It's refreshing.",
 'My favourite computer based band is the Black IPs.',
 "Why was the developer bankrupt? He'd used all his cache.",
 "A friend is in a band called 1023Mb. They haven't had a gig yet.",
 "Apparently my password needs to be capitals only so I've changed it to LONDONMADRIDROME",
 "I changed my password to BeefStew but the computer told me it wasn't Stroganoff.",
 "Changed my password to fortnight but apparently that's two week.",
 'Artificial intelligence usually beats real stupidity.',
 'The Internet: where men are men, women are men, and children are FBI agents.',
 'Bugs come in through open Windows.',
 "Unix is user friendly. It's just selective about who its friends are.",
 'Failure is not an option. It comes bundled with your Microsoft product.',
 'Computers are like air conditioners: they stop working when you open Windows.',
 'Beware of programmers that carry screwdrivers.',
 "I'm not anti-social; I'm just not user friendly.",
 'Hey! It compiles! Ship it!',
 "If Ruby is not and Perl is the answer, you don't understand the question.",
 "My attitude isn't bad. It's in beta.",
 'Programmers are tools for converting caffeine into code.',
 "There are three kinds of people: those who can count and those who can't.",
 'Why do programmers prefer dark mode? Because light attracts bugs.']

## Common Third Party Libraries in Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- SciPy
- Scikit-learn

## Numpy

In [ ]:
# Creating a list of 1,000,000 salaries ranging from 50,000 to 150,000

import random

salary_list = [random.randint(50000, 150000) for i in range(1_000_000)]

In [ ]:
import statistics

In [ ]:
%%timeit
statistics.mean(salary_list)

510 ms ± 317 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
print(statistics.mean(salary_list))

100039.90263

In [ ]:
import numpy as np

In [ ]:
%%timeit
np.mean(salary_list)

52.4 ms ± 885 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
print(np.mean(salary_list))

100039.90263

In [ ]:
import numpy as np

my_array = np.array([1, 2, 3, 4])

print(np.mean(my_array))

2.5

In [ ]:
# Job Titles
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer'])

# Base Salaries
base_salaries = np.array([60000, 80000, 75000, 90000])

# Bonus Rates
bonus_rates = np.array([0.05, 0.1, 0.08, 0.12])

In [ ]:
# Calculating the total salaries for the above array items

total_salaries = base_salaries * (1 + bonus_rates)

total_salaries

array([ 63000.,  88000.,  81000., 100800.])

In [ ]:
print(np.mean(total_salaries))

83200.0

In [ ]:
"""
Suppose, another job title is to be added in the above example and we do not know the base_salary and bonus_rate for the same, then
use the 'nan' constant to define the null value.
nan stands for 'Not a Number'
"""

type(None)

NoneType

In [ ]:
# Job Titles
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer', 'AI Engineer'])

# Defining 'None' doesn't help because (1+None) can't be formulated

# Base Salaries
base_salaries = np.array([60000, 80000, 75000, 90000, None])

# Bonus Rates
bonus_rates = np.array([0.05, 0.1, 0.08, 0.12, None])

# Calculating the total salaries for the above array items

total_salaries = base_salaries * (1 + bonus_rates)

total_salaries

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [ ]:
# Job Titles
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer', 'AI Engineer'])

# Base Salaries
base_salaries = np.array([60000, 80000, 75000, 90000, np.nan])

# Bonus Rates
bonus_rates = np.array([0.05, 0.1, 0.08, 0.12, np.nan])

# Calculating the total salaries for the above array items

total_salaries = base_salaries * (1 + bonus_rates)

print(total_salaries)

print(np.nanmean(total_salaries))

[ 63000.  88000.  81000. 100800.     nan]
83200.0

## Back to Pandas

In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_test.csv')

df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
df['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
df.total_rooms

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [ ]:
print(df.total_bedrooms[0])
print(df['total_bedrooms'][0])

661.0
661.0

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset('lukebarousse/data_jobs')

In [ ]:
df = dataset['train'].to_pandas()
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB