In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

c:\Users\Shivangi\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [5]:
median_salary_year = df['salary_year_avg'].median()

In [6]:
median_salary_hour = df['salary_hour_avg'].median()

In [13]:
df_filled = df

df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(value = median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(value = median_salary_hour)

In [14]:
df_filled['salary_year_avg']

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64

In [15]:
df_filled['salary_hour_avg']

0         45.98
1         45.98
2         45.98
3         45.98
4         45.98
          ...
785736    45.98
785737    45.98
785738    45.98
785739    45.98
785740    45.98
Name: salary_hour_avg, Length: 785741, dtype: float64

In [18]:
df_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [24]:
df_unique = df_filled
df_unique = df_unique.drop_duplicates()

In [25]:
print("Original no. of rows: ", len(df_filled))
print("Unique no. of rows:   ", len(df_unique))
print("No. of rows dropped:  ", len(df_filled) - len(df_unique))

Original no. of rows:  785741
Unique no. of rows:    785640
No. of rows dropped:   101

In [ ]:
# The subset parameter defines which specific column or group of columns pandas should check to identify duplicate rows.
df_unique = df_unique.drop_duplicates(subset = ['job_title', 'company_name'])

print("Original no. of rows: ", len(df_filled))
print("Unique no. of rows:   ", len(df_unique))
print("No. of rows dropped:  ", len(df_filled) - len(df_unique))

Original no. of rows:  785741
Unique no. of rows:    508042
No. of rows dropped:   277699