In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

c:\Users\Shivangi\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [3]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [4]:
# To return a random sample of items from an axis of objects, use the sample method; ex: df.sample(n)
# 'n' represents the number of samples you want

df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
309363,Business Analyst,Adobe Analyst,"San Antonio, TX",via LinkedIn,Contractor,False,"Texas, United States",2023-06-14 17:01:51,True,False,United States,NaN,NaN,NaN,Quantum World Technologies Inc.,['hadoop'],{'libraries': ['hadoop']}
589792,Data Analyst,Data Analyst I,Missouri,via Dwamk,Full-time,False,"Illinois, United States",2023-12-22 09:01:26,False,True,United States,NaN,NaN,NaN,TEKsystems,"['sql', 'python', 'sql server', 'azure', 'aws'...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
91027,Data Scientist,Data Scientist / Artificial Intelligence m/f,France,via Jobrapido.com,Full-time,False,France,2023-01-29 00:16:21,False,False,France,NaN,NaN,NaN,Unspecified,"['python', 'r', 'sql', 'sas', 'sas', 'pyspark']","{'analyst_tools': ['sas'], 'libraries': ['pysp..."
487362,Data Engineer,Internship - Data Engineer,Singapore,via LinkedIn,Internship,False,Singapore,2023-02-27 11:09:13,False,False,Singapore,NaN,NaN,NaN,Infineon Technologies,"['python', 'sql', 'c']","{'programming': ['python', 'sql', 'c']}"
695242,Senior Data Engineer,Senior Data Engineer - Shared Products & Platf...,"Stockholm, Sweden",via LinkedIn,Full-time,False,Sweden,2023-01-08 10:36:30,True,False,Sweden,NaN,NaN,NaN,Schibsted,"['python', 'scala', 'java', 'kotlin', 'aws', '...","{'cloud': ['aws', 'snowflake'], 'libraries': [..."
646726,Data Scientist,Data Scientist II,Anywhere,via LinkedIn,Full-time,True,Mexico,2023-12-29 12:15:03,False,False,Mexico,NaN,NaN,NaN,Zillow,"['python', 'sql', 'word']","{'analyst_tools': ['word'], 'programming': ['p..."
76390,Data Engineer,Data Engineer,India,via Bayt.com,Full-time,False,India,2023-05-31 00:11:11,False,False,India,NaN,NaN,NaN,Databricks,"['python', 'scala', 'sql', 'databricks', 'hado...","{'analyst_tools': ['tableau', 'looker', 'excel..."
547794,Cloud Engineer,Data Platform Architect,"Vancouver, BC, Canada",via Trabajo.org,Full-time,False,Canada,2023-03-29 19:37:17,True,False,Canada,NaN,NaN,NaN,HP,NaN,NaN
373171,Senior Data Engineer,Senior Data Integration Engineer - Data Engine...,"Bloomington, MN",via Snagajob,Full-time and Part-time,False,"Florida, United States",2023-09-28 18:46:26,False,False,United States,hour,NaN,50.965,Donaldson Company,"['sql', 'no-sql', 'snowflake', 'oracle', 'azur...","{'cloud': ['snowflake', 'oracle', 'azure'], 'o..."
714947,Data Engineer,Data Engineer,"North Jakarta, North Jakarta City, Jakarta, In...",via Glints,Contractor,False,Indonesia,2023-12-15 02:20:53,True,False,Indonesia,NaN,NaN,NaN,PT Karisma Zona Kreatifku (KAZOKKU),"['nosql', 'python', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."

In [16]:
# To return the same result everytime you use the sample() method, specifiy the 'random_state' parameter

df.sample(10, random_state = 32)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
726955,Data Analyst,Data Analyst,"Atlanta, GA",via LinkedIn,Full-time,False,Georgia,2023-06-08 21:46:27,False,False,United States,NaN,NaN,NaN,Troutman Pepper,"['sql', 'python', 'r', 'sql server', 'azure', ...","{'analyst_tools': ['power bi', 'alteryx', 'exc..."
640874,Data Analyst,Market Data,"Kraków, Poland",via Trabajo.org,Full-time,False,Poland,2023-02-14 12:37:43,True,False,Poland,NaN,NaN,NaN,Grafton Recruitment Sp. z o.o.,"['c', 'linux']","{'os': ['linux'], 'programming': ['c']}"
133115,Business Analyst,Growth Analyst,Spain,via LinkedIn,Full-time,False,Spain,2023-07-14 08:22:56,True,False,Spain,NaN,NaN,NaN,Indicia Worldwide,"['html', 'css', 'javascript']","{'programming': ['html', 'css', 'javascript']}"
231903,Senior Data Scientist,"Senior Manager, Data Science","McLean, VA",via Trabajo.org,Full-time,False,"New York, United States",2023-10-25 07:03:26,False,False,United States,NaN,NaN,NaN,Cognosante,NaN,NaN
511218,Software Engineer,Re-advertisement: Senior Systems Analyst (24 M...,Saudi Arabia,via Jobs In South Africa,Full-time,False,Saudi Arabia,2023-06-27 11:42:23,False,False,Saudi Arabia,NaN,NaN,NaN,Rand Water,"['oracle', 'sap']","{'analyst_tools': ['sap'], 'cloud': ['oracle']}"
770498,Data Scientist,Data Scientist - Shuzhao Li,"Farmington, CT",via LinkedIn,Full-time,False,"New York, United States",2023-01-26 01:03:06,False,False,United States,NaN,NaN,NaN,The Jackson Laboratory,"['python', 'r']","{'programming': ['python', 'r']}"
408161,Data Engineer,Cloud Data Engineer,India,via BeBee India,Full-time,False,India,2023-05-16 16:17:10,False,False,India,NaN,NaN,NaN,Ericsson,"['shell', 'scala', 'python', 'java', 'airflow'...","{'libraries': ['airflow', 'pyspark', 'spark', ..."
61685,Software Engineer,IT Engineer,"Bogotá, Bogota, Colombia",via BeBee,Full-time,False,Colombia,2023-08-23 06:28:09,True,False,Colombia,NaN,NaN,NaN,jobandtalent,"['sql', 'go', 'mysql', 'oracle']","{'cloud': ['oracle'], 'databases': ['mysql'], ..."
496542,Business Analyst,Analist indicatoren,"Brussels, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-10-09 11:50:37,False,False,Belgium,NaN,NaN,NaN,Actiris,NaN,NaN
1856,Data Scientist,Data Scientist III - Product Lifecycle & Inter...,"Barcelona, Spain",via LinkedIn,Full-time,False,Spain,2023-03-07 13:44:13,False,False,Spain,NaN,NaN,NaN,Teladoc Health,"['python', 'sql', 'pytorch', 'tensorflow', 'sp...","{'libraries': ['pytorch', 'tensorflow', 'spark..."

In [17]:
# To make the a of an object's indices and data, use the copy() method

dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [18]:
df_original

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [20]:
df_altered = df_original

df_altered.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [22]:
median_salary = df_altered['salary_year_avg'].median()

median_salary

np.float64(115000.0)

In [23]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

In [24]:
df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [25]:
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [26]:
print(id(df_original))
print(id(df_altered))

2220657649168
2220657649168

Hence from above, we conclude that the operations performed on df_altered were being performed over df_original as well which is a bad practice

In [27]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [28]:
df_altered = df_original.copy()

In [29]:
print(id(df_original))
print(id(df_altered))

2220936199248
2220936114128

In [30]:
median_salary = df_altered['salary_year_avg'].median()

median_salary

np.float64(115000.0)

In [32]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [33]:
df_original.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64