In [2]:
# Importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [5]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
323815,Data Engineer,Lead Data Engineer,"Florianópolis, State of Santa Catarina, Brazil",via BeBee,Full-time,False,Brazil,2023-10-13 18:06:00,True,False,Brazil,NaN,NaN,NaN,MonetizeMore,"['sql', 'python', 'aws', 'azure', 'airflow', '...","{'cloud': ['aws', 'azure'], 'libraries': ['air..."
200369,Cloud Engineer,Managed Services Engineer,"Bunnik, Netherlands",via LinkedIn,Full-time,False,Netherlands,2023-03-01 15:30:50,False,False,Netherlands,NaN,NaN,NaN,Data Management Professionals (DMP),NaN,NaN
192232,Data Scientist,"Intern, Data Science","Chicago, IL",via Huzzle,Full-time and Internship,False,"Illinois, United States",2023-12-18 15:03:07,False,False,United States,NaN,NaN,NaN,Strata Decision Technology,"['python', 'sql', 'spring']","{'libraries': ['spring'], 'programming': ['pyt..."
259947,Software Engineer,IT Support,"Samut Sakhon, Thailand",via JobThai,Full-time,False,Thailand,2023-02-20 07:57:40,True,False,Thailand,NaN,NaN,NaN,บริษัท เอเอสเอ คอนเทนเนอร์ จำกัด,NaN,NaN
120316,Data Analyst,Procurement Data Analyst Student,Canada,via BeBee Canada,Full-time,False,Canada,2023-06-12 08:30:56,False,False,Canada,NaN,NaN,NaN,PCL Construction,"['power bi', 'excel']","{'analyst_tools': ['power bi', 'excel']}"

In [6]:
# df.index
df.index.name

In [7]:
df.index.name = 'job_index'

In [8]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
346086,Software Engineer,Principal engineer,Argentina,via Sercanto,Full-time,False,Argentina,2023-04-12 23:34:35,True,False,Argentina,NaN,NaN,NaN,Kin + Carta,NaN,NaN
604591,Software Engineer,Dir-Solutions Specialist,Canada,via ZipRecruiter,Full-time,False,Canada,2023-04-30 09:16:48,False,False,Canada,NaN,NaN,NaN,Moody's,NaN,NaN
702701,Data Engineer,Data Engineer,"Kuala Lumpur, Federal Territory of Kuala Lumpu...",via LinkedIn,NaN,False,Malaysia,2023-07-12 03:15:46,False,False,Malaysia,NaN,NaN,NaN,Dropee,"['sql', 'aws', 'gcp', 'azure']","{'cloud': ['aws', 'gcp', 'azure'], 'programmin..."
733437,Data Analyst,Data Analyst Jobs In Sharjah,Sharjah - United Arab Emirates,via BeBee,Full-time,False,United Arab Emirates,2023-11-14 21:44:19,False,False,United Arab Emirates,NaN,NaN,NaN,Kintlogix LLC,NaN,NaN
602465,Data Analyst,Marketing Data Analyst,"Las Vegas, NV",via ZipRecruiter,Full-time,False,"California, United States",2023-09-30 09:01:12,False,False,United States,hour,NaN,22.555,Silver State Schools Credit Union,['c'],{'programming': ['c']}

In [9]:
df.index.dtype

dtype('int64')

## reset_index()

In [11]:
df_india = df[df['job_country'] == 'India']
df_india.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-06-15 13:28:03,False,False,India,NaN,NaN,NaN,Hexaware Technologies,"['powershell', 'python', 'sql', 'mysql', 'sql ...","{'cloud': ['databricks', 'azure'], 'databases'..."
19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,NaN,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,NaN,NaN,NaN,Exusia,NaN,NaN
38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,NaN,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
42,Senior Data Engineer,"Senior Data Engineer(Python)-1563,1637&1633","Chennai, Tamil Nadu, India",via HR Software For Growing Businesses | Fresh...,Full-time,False,India,2023-11-10 13:30:41,True,False,India,NaN,NaN,NaN,CESIT,"['python', 'sql', 'aws', 'pyspark', 'docker', ...","{'async': ['jira'], 'cloud': ['aws'], 'librari..."

In [12]:
# inplace: Whether to modify the dataframe rather than creating a new one

df_india.reset_index(inplace = True)

df_india.head()

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-06-15 13:28:03,False,False,India,NaN,NaN,NaN,Hexaware Technologies,"['powershell', 'python', 'sql', 'mysql', 'sql ...","{'cloud': ['databricks', 'azure'], 'databases'..."
1,19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,NaN,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
2,29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,NaN,NaN,NaN,Exusia,NaN,NaN
3,38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,NaN,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
4,42,Senior Data Engineer,"Senior Data Engineer(Python)-1563,1637&1633","Chennai, Tamil Nadu, India",via HR Software For Growing Businesses | Fresh...,Full-time,False,India,2023-11-10 13:30:41,True,False,India,NaN,NaN,NaN,CESIT,"['python', 'sql', 'aws', 'pyspark', 'docker', ...","{'async': ['jira'], 'cloud': ['aws'], 'librari..."

## set_index()

Set the dataframe index using the existing columns

In [14]:
df_india.set_index('job_index', inplace = True)

df_india.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-06-15 13:28:03,False,False,India,NaN,NaN,NaN,Hexaware Technologies,"['powershell', 'python', 'sql', 'mysql', 'sql ...","{'cloud': ['databricks', 'azure'], 'databases'..."
19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,NaN,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,NaN,NaN,NaN,Exusia,NaN,NaN
38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,NaN,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
42,Senior Data Engineer,"Senior Data Engineer(Python)-1563,1637&1633","Chennai, Tamil Nadu, India",via HR Software For Growing Businesses | Fresh...,Full-time,False,India,2023-11-10 13:30:41,True,False,India,NaN,NaN,NaN,CESIT,"['python', 'sql', 'aws', 'pyspark', 'docker', ...","{'async': ['jira'], 'cloud': ['aws'], 'librari..."

## sort_index()

Returns a new dataframe sorted by label if 'inplace' argument is 'False', otherwise updates the original dataframe and returns None

In [15]:
median_pivot = df_india.pivot_table(index = 'job_title_short', values = 'salary_year_avg', aggfunc = ['median', 'min', 'max'])
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  64800.0         43200.0        142025.0
Data Analyst                     100500.0         32400.0        650000.0
Data Engineer                    147500.0         43200.0        249000.0
Data Scientist                   114008.0         43200.0        204381.0
Machine Learning Engineer         79200.0         32500.0        267000.0
Senior Data Analyst              111175.0         64800.0        177283.0
Senior Data Engineer             147500.0         35000.0        181765.0
Senior Data Scientist            149653.0         64800.0        170575.0
Software Engineer                 79200.0         44418.5        200000.0

In [18]:
median_pivot.sort_values(by = ('median', 'salary_year_avg'), ascending = False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            149653.0         64800.0        170575.0
Senior Data Engineer             147500.0         35000.0        181765.0
Data Engineer                    147500.0         43200.0        249000.0
Data Scientist                   114008.0         43200.0        204381.0
Senior Data Analyst              111175.0         64800.0        177283.0
Data Analyst                     100500.0         32400.0        650000.0
Machine Learning Engineer         79200.0         32500.0        267000.0
Software Engineer                 79200.0         44418.5        200000.0
Business Analyst                  64800.0         43200.0        142025.0

In [19]:
# Now using the sort_index() function

median_pivot.sort_index()

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  64800.0         43200.0        142025.0
Data Analyst                     100500.0         32400.0        650000.0
Data Engineer                    147500.0         43200.0        249000.0
Data Scientist                   114008.0         43200.0        204381.0
Machine Learning Engineer         79200.0         32500.0        267000.0
Senior Data Analyst              111175.0         64800.0        177283.0
Senior Data Engineer             147500.0         35000.0        181765.0
Senior Data Scientist            149653.0         64800.0        170575.0
Software Engineer                 79200.0         44418.5        200000.0