In [1]:
import pandas as pd

jobs_jan = {
    'job_id': [1, 2, 3, 4, 5],
    'job_title': ['Data Scientist', 'Data Analyst', 'ML Engineer', 'Data Scientist', 'Data Engineer'],
    'company': ['Company A', 'Company B', 'Company C', 'Company D', 'Company E'],
    'job_posted_date': ['2024-01-02', '2024-01-07', '2024-01-14', '2024-01-19', '2024-01-24']
}

job_postings_jan = pd.DataFrame(jobs_jan)
job_postings_jan

   job_id       job_title    company job_posted_date
0       1  Data Scientist  Company A      2024-01-02
1       2    Data Analyst  Company B      2024-01-07
2       3     ML Engineer  Company C      2024-01-14
3       4  Data Scientist  Company D      2024-01-19
4       5   Data Engineer  Company E      2024-01-24

In [2]:
jobs_feb = {
    'job_id': [6, 7, 8, 9, 10],
    'job_title': [
        'Data Scientist', 
        'Data Analyst', 
        'ML Engineer', 
        'Data Scientist', 
        'Data Engineer'
    ],
    'company': [
        'Company F', 
        'Company G', 
        'Company H', 
        'Company I', 
        'Company J'
    ],
    'job_posted_date': [
        '2024-02-05', 
        '2024-02-09', 
        '2024-02-12', 
        '2024-02-18', 
        '2024-02-22'
    ]
}

job_postings_feb = pd.DataFrame(jobs_feb)
job_postings_feb

   job_id       job_title    company job_posted_date
0       6  Data Scientist  Company F      2024-02-05
1       7    Data Analyst  Company G      2024-02-09
2       8     ML Engineer  Company H      2024-02-12
3       9  Data Scientist  Company I      2024-02-18
4      10   Data Engineer  Company J      2024-02-22

In [3]:
job_postings_jan.merge(job_postings_feb, on = 'job_title', suffixes = ('_jan', '_feb'))

,job_id_jan,job_title,company_jan,job_posted_date_jan,job_id_feb,company_feb,job_posted_date_feb
0,1,Data Scientist,Company A,2024-01-02,6,Company F,2024-02-05
1,1,Data Scientist,Company A,2024-01-02,9,Company I,2024-02-18
2,4,Data Scientist,Company D,2024-01-19,6,Company F,2024-02-05
3,4,Data Scientist,Company D,2024-01-19,9,Company I,2024-02-18
4,2,Data Analyst,Company B,2024-01-07,7,Company G,2024-02-09
5,3,ML Engineer,Company C,2024-01-14,8,Company H,2024-02-12
6,5,Data Engineer,Company E,2024-01-24,10,Company J,2024-02-22

In [4]:
pd.concat([job_postings_jan, job_postings_feb])

   job_id       job_title    company job_posted_date
0       1  Data Scientist  Company A      2024-01-02
1       2    Data Analyst  Company B      2024-01-07
2       3     ML Engineer  Company C      2024-01-14
3       4  Data Scientist  Company D      2024-01-19
4       5   Data Engineer  Company E      2024-01-24
0       6  Data Scientist  Company F      2024-02-05
1       7    Data Analyst  Company G      2024-02-09
2       8     ML Engineer  Company H      2024-02-12
3       9  Data Scientist  Company I      2024-02-18
4      10   Data Engineer  Company J      2024-02-22

In [5]:
pd.concat([job_postings_jan, job_postings_feb], ignore_index = True)

   job_id       job_title    company job_posted_date
0       1  Data Scientist  Company A      2024-01-02
1       2    Data Analyst  Company B      2024-01-07
2       3     ML Engineer  Company C      2024-01-14
3       4  Data Scientist  Company D      2024-01-19
4       5   Data Engineer  Company E      2024-01-24
5       6  Data Scientist  Company F      2024-02-05
6       7    Data Analyst  Company G      2024-02-09
7       8     ML Engineer  Company H      2024-02-12
8       9  Data Scientist  Company I      2024-02-18
9      10   Data Engineer  Company J      2024-02-22

In [6]:
# Importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

ModuleNotFoundError: No module named 'datasets'

In [ ]:
df['job_posted_month'] = df['job_posted_date'].dt.strftime('%b')